### ISSUE TITLE
Payments form: label for "delivery-address-differs" is v big yo

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/maerkelex.dk#128]
On branch `payments`. It interferes with clicking on labels and makes users confused:

![label-is-big](https://cloud.githubusercontent.com/assets/859106/24103760/9000e31a-0d80-11e7-8441-8eb2688e0f1e.png)

**Comment by Arth101** [comment]
Fixed bro :).
Float was to blame!

![untitled-1](https://cloud.githubusercontent.com/assets/8166831/24590728/a6b6e650-17f2-11e7-9c67-3ba895e793a4.jpg)

**Comment by hypesystem** [comment]
noice
