### ISSUE TITLE
Nye KFUM mærker

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/maerkelex.dk#169]
@Arth101  har du evt tid til at se på disse mærker?

**Flaget**

- https://spejdernet.dk/badges/flaget/
- https://www.55nord.dk/kfum-spejderne/shop/faerdighedsmaerker/flaget-trop-og-senior

**Øksebevis**

- https://spejdernet.dk/badges/oeksebevis/
- https://www.55nord.dk/kfum-spejderne/shop/faerdighedsmaerker/oeksebevis-junior

Jeg skal nok lave en fb update når de er oppe :smile:

**Comment by Arth101** [comment]
THis is done
